export default {
    "success": true,
    "data": {
        "cities": [
            {
                "id": "1",
                "desc": "berlin",
                "airport": "BER",
                "webp": "src/assets/images/webp/berlin.webp",
                "jpeg": "public/assets/images/jpeg/berlin.jpeg",
                "sectionCss": "snap-start w-full h-screen flex items-center justify-center bg-berlin",
                "imgCss": "w-auto h-1/3 md:h-1/2 drop-shadow-2xl",
            },
            {
                "id": "2",
                "city": "paris",
                "color": "paris",
                "airport": "PAR",
                "webp": "src/assets/images/webp/paris.webp",
                "jpeg": "public/assets/images/jpeg/paris.jpeg",
                "sectionCss": "snap-start w-full h-screen flex items-center justify-center bg-paris",
                "imgCss": "w-auto h-1/3 md:h-1/2 drop-shadow-2xl",
            },
            {
                "id": "3",
                "city": "amsterdam",
                "color": "amsterdam",
                "airport": "AMS",
                "webp": "src/assets/images/webp/amsterdam.webp",
                "jpeg": "public/assets/images/jpeg/amsterdam.jpeg",
                "sectionCss": "snap-start w-full h-screen flex items-center justify-center bg-amsterdam",
                "imgCss": "w-auto h-1/3 md:h-1/2 drop-shadow-2xl",
            },
            {
                "id": "4",
                "city": "london",
                "color": "london",
                "airport": "LON",
                "webp": "src/assets/images/webp/london.webp",
                "jpeg": "public/assets/images/jpeg/london.jpeg",
                "sectionCss": "snap-start w-full h-screen flex items-center justify-center bg-london",
                "imgCss": "w-auto h-1/3 md:h-1/2 drop-shadow-2xl",
            },
            {
                "id": "5",
                "city": "vienna",
                "color": "vienna",
                "airport": "VIE",
                "webp": "src/assets/images/webp/vienna.webp",
                "jpeg": "public/assets/images/jpeg/vienna.jpeg",
                "sectionCss": "snap-start w-full h-screen flex items-center justify-center bg-vienna",
                "imgCss": "w-auto h-1/3 md:h-1/2 drop-shadow-2xl",
            },
            {
                "id": "6",
                "city": "milan",
                "color": "milan",
                "airport": "MIL",
                "webp": "src/assets/images/webp/milan.webp",
                "jpeg": "public/assets/images/jpeg/milan.jpeg",
                "sectionCss": "snap-start w-full h-screen flex items-center justify-center bg-milan",
                "imgCss": "w-auto h-1/3 md:h-1/2 drop-shadow-2xl",
            },
            {
                "id": "7",
                "city": "barcelona",
                "color": "barcelona",
                "airport": "BCN",
                "webp": "src/assets/images/webp/barcelona.webp",
                "jpeg": "public/assets/images/jpeg/barcelona.jpeg",
                "sectionCss": "snap-start w-full h-screen flex items-center justify-center bg-barcelona",
                "imgCss": "w-auto h-1/3 md:h-1/2 drop-shadow-2xl",
            },
            {
                "id": "8",
                "city": "nyc",
                "color": "nyc",
                "airport": "NYC",
                "webp": "src/assets/images/webp/nyc.webp",
                "jpeg": "public/assets/images/jpeg/nyc.jpeg",
                "sectionCss": "snap-start w-full h-screen flex items-center justify-center bg-nyc",
                "imgCss": "w-auto h-1/3 md:h-1/2 drop-shadow-2xl",
            },
            {
                "id": "9",
                "city": "frankfurt",
                "color": "frankfurt",
                "airport": "FRA",
                "webp": "src/assets/images/webp/frankfurt.webp",
                "jpeg": "public/assets/images/jpeg/frankfurt.jpeg",
                "sectionCss": "snap-start w-full h-screen flex items-center justify-center bg-frankfurt",
                "imgCss": "w-auto h-1/3 md:h-1/2 drop-shadow-2xl",
            },
            {
                "id": "10",
                "city": "stockholm",
                "color": "stockholm",
                "airport": "STO",
                "webp": "src/assets/images/webp/stockholm.webp",
                "jpeg": "public/assets/images/jpeg/stockholm.jpeg",
                "sectionCss": "snap-start w-full h-screen flex items-center justify-center bg-stockholm",
                "imgCss": "w-auto h-1/3 md:h-1/2 drop-shadow-2xl",
            },
            {
                "id": "11",
                "city": "los-angeles",
                "airport": "LAX",
                "webp": "src/assets/images/webp/la.webp",
                "jpeg": "public/assets/images/jpeg/la.jpeg",
                "sectionCss": "snap-start w-full h-screen flex items-center justify-center bg-la",
                "imgCss": "w-auto h-1/3 md:h-1/2 drop-shadow-2xl",
            },
            {
                "id": "12",
                "city": "ibiza",
                "airport": "IBZ",
                "webp": "src/assets/images/webp/ibiza.webp",
                "jpeg": "public/assets/images/jpeg/ibiza.jpeg",
                "sectionCss": "snap-start w-full h-screen flex items-center justify-center bg-ibiza",
                "imgCss": "w-auto h-1/3 md:h-1/2 drop-shadow-2xl",
            },
            {
                "id": "13",
                "city": "lisbon",
                "color": "lisbon",
                "airport": "LIS",
                "webp": "src/assets/images/webp/lisbon.webp",
                "jpeg": "public/assets/images/jpeg/lisbon.jpeg",
                "sectionCss": "snap-start w-full h-screen flex items-center justify-center bg-lisbon",
                "imgCss": "w-auto h-1/3 md:h-1/2 drop-shadow-2xl",
            },
            {
                "id": "14",
                "city": "copenhagen",
                "color": "copenhagen",
                "airport": "CPH",
                "webp": "src/assets/images/webp/copenhagen.webp",
                "jpeg": "public/assets/images/jpeg/copenhagen.jpeg",
                "sectionCss": "snap-start w-full h-screen flex items-center justify-center bg-copenhagen",
                "imgCss": "w-auto h-1/3 md:h-1/2 drop-shadow-2xl",
            },
            {
                "id": "16",
                "city": "zurich",
                "color": "zurich",
                "airport": "ZRH",
                "webp": "src/assets/images/webp/zurich.webp",
                "jpeg": "public/assets/images/jpeg/zurich.jpeg",
                "sectionCss": "snap-start w-full h-screen flex items-center justify-center bg-zurich",
                "imgCss": "w-auto h-1/3 md:h-1/2 drop-shadow-2xl",
            },
            {
                "id": "17",
                "city": "miami",
                "color": "miami",
                "airport": "MIA",
                "webp": "src/assets/images/webp/miami.webp",
                "jpeg": "public/assets/images/jpeg/miami.jpeg",
                "sectionCss": "snap-start w-full h-screen flex items-center justify-center bg-miami",
                "imgCss": "w-auto h-1/3 md:h-1/2 drop-shadow-2xl",
            },
            {
                "id": "18",
                "city": "tokyo",
                "color": "tokyo",
                "airport": "TYO",
                "webp": "src/assets/images/webp/tokyo.webp",
                "jpeg": "public/assets/images/jpeg/tokyo.jpeg",
                "sectionCss": "snap-start w-full h-screen flex items-center justify-center bg-tokyo",
                "imgCss": "w-auto h-1/3 md:h-1/2 drop-shadow-2xl",
            },
            {
                "id": "19",
                "city": "buenos-aires",
                "color": "buenos-aires",
                "airport": "EZE",
                "webp": "src/assets/images/webp/buenos-aires.webp",
                "jpeg": "public/assets/images/jpeg/buenos-aires.jpeg",
                "sectionCss": "snap-start w-full h-screen flex items-center justify-center bg-buenos-aires",
                "imgCss": "w-auto h-1/3 md:h-1/2 drop-shadow-2xl",
            },
            {
                "id": "20",
                "city": "istanbul",
                "color": "istanbul",
                "airport": "IST",
                "webp": "src/assets/images/webp/istanbul.webp",
                "jpeg": "public/assets/images/jpeg/istanbul.jpeg",
                "sectionCss": "snap-start w-full h-screen flex items-center justify-center bg-istanbul",
                "imgCss": "w-auto h-1/3 md:h-1/2 drop-shadow-2xl",
            },
            {
                "id": "21",
                "city": "seoul",
                "color": "seoul",
                "airport": "ICN",
                "webp": "src/assets/images/webp/seoul.webp",
                "jpeg": "public/assets/images/jpeg/seoul.jpeg",
                "sectionCss": "snap-start w-full h-screen flex items-center justify-center bg-seoul",
                "imgCss": "w-auto h-1/3 md:h-1/2 drop-shadow-2xl",
            },
            {
                "id": "22",
                "city": "detroit",
                "color": "detroit",
                "airport": "DTT",
                "webp": "src/assets/images/webp/detroit.webp",
                "jpeg": "public/assets/images/jpeg/detroit.jpeg",
                "sectionCss": "snap-start w-full h-screen flex items-center justify-center bg-detroit",
                "imgCss": "w-auto h-1/3 md:h-1/2 drop-shadow-2xl",
            },
        ]

    }
}
