export default {
    "success": true,
    "data": {
        "cities": [
            {
                "id": "1",
                "desc": "berlin",
                "issue": "#1",
                "url": "src/assets/images/berlin.webp",
                "sectionCss": "snap-start w-full h-screen flex items-center justify-center bg-berlin",
                "imgCss": "w-auto h-1/3 md:h-1/2 drop-shadow-2xl",
            },
            {
                "id": "2",
                "city": "paris",
                "color": "paris",
                "issue": "#2",
                "url": "src/assets/images/paris.webp",
                "sectionCss": "snap-start w-full h-screen flex items-center justify-center bg-paris",
                "imgCss": "w-auto h-1/3 md:h-1/2 drop-shadow-2xl",
            },
            {
                "id": "3",
                "city": "amsterdam",
                "color": "amsterdam",
                "issue": "#3",
                "url": "src/assets/images/amsterdam.webp",
                "sectionCss": "snap-start w-full h-screen flex items-center justify-center bg-amsterdam",
                "imgCss": "w-auto h-1/3 md:h-1/2 drop-shadow-2xl",
            },
            {
                "id": "4",
                "city": "london",
                "color": "london",
                "issue": "#4",
                "url": "src/assets/images/london.webp",
                "sectionCss": "snap-start w-full h-screen flex items-center justify-center bg-london",
                "imgCss": "w-auto h-1/3 md:h-1/2 drop-shadow-2xl",
            },
            {
                "id": "5",
                "city": "vienna",
                "color": "vienna",
                "issue": "#5",
                "url": "src/assets/images/vienna.webp",
                "sectionCss": "snap-start w-full h-screen flex items-center justify-center bg-vienna",
                "imgCss": "w-auto h-1/3 md:h-1/2 drop-shadow-2xl",
            },
            {
                "id": "6",
                "city": "milan",
                "color": "milan",
                "issue": "#6",
                "url": "src/assets/images/milan.webp",
                "sectionCss": "snap-start w-full h-screen flex items-center justify-center bg-milan",
                "imgCss": "w-auto h-1/3 md:h-1/2 drop-shadow-2xl",
            },
            {
                "id": "7",
                "city": "barcelona",
                "color": "barcelona",
                "issue": "#7",
                "url": "src/assets/images/barcelona.webp",
                "sectionCss": "snap-start w-full h-screen flex items-center justify-center bg-barcelona",
                "imgCss": "w-auto h-1/3 md:h-1/2 drop-shadow-2xl",
            },
            {
                "id": "8",
                "city": "nyc",
                "color": "nyc",
                "issue": "#8",
                "url": "src/assets/images/nyc.webp",
                "sectionCss": "snap-start w-full h-screen flex items-center justify-center bg-nyc",
                "imgCss": "w-auto h-1/3 md:h-1/2 drop-shadow-2xl",
            },
            {
                "id": "9",
                "city": "frankfurt",
                "color": "frankfurt",
                "issue": "#9",
                "url": "src/assets/images/frankfurt.webp",
                "sectionCss": "snap-start w-full h-screen flex items-center justify-center bg-frankfurt",
                "imgCss": "w-auto h-1/3 md:h-1/2 drop-shadow-2xl",
            },
            {
                "id": "10",
                "city": "stockholm",
                "color": "stockholm",
                "issue": "#10",
                "url": "src/assets/images/stockholm.webp",
                "sectionCss": "snap-start w-full h-screen flex items-center justify-center bg-stockholm",
                "imgCss": "w-auto h-1/3 md:h-1/2 drop-shadow-2xl",
            },
            {
                "id": "11",
                "city": "los-angeles",
                "issue": "#11",
                "url": "src/assets/images/la.webp",
                "sectionCss": "snap-start w-full h-screen flex items-center justify-center bg-la",
                "imgCss": "w-auto h-1/3 md:h-1/2 drop-shadow-2xl",
            },
            {
                "id": "12",
                "city": "ibiza",
                "issue": "#12",
                "url": "src/assets/images/ibiza.webp",
                "sectionCss": "snap-start w-full h-screen flex items-center justify-center bg-ibiza",
                "imgCss": "w-auto h-1/3 md:h-1/2 drop-shadow-2xl",
            },
            {
                "id": "13",
                "city": "lisbon",
                "color": "lisbon",
                "issue": "#13",
                "url": "src/assets/images/lisbon.webp",
                "sectionCss": "snap-start w-full h-screen flex items-center justify-center bg-lisbon",
                "imgCss": "w-auto h-1/3 md:h-1/2 drop-shadow-2xl",
            },
            {
                "id": "14",
                "city": "copenhagen",
                "color": "copenhagen",
                "issue": "#14",
                "url": "src/assets/images/copenhagen.webp",
                "sectionCss": "snap-start w-full h-screen flex items-center justify-center bg-copenhagen",
                "imgCss": "w-auto h-1/3 md:h-1/2 drop-shadow-2xl",
            },
            {
                "id": "15",
                "city": "warsaw",
                "color": "warsaw",
                "issue": "#15",
                "url": "src/assets/images/warsaw.png",
                "sectionCss": "snap-start w-full h-screen flex items-center justify-center bg-warsaw",
                "imgCss": "w-auto h-1/3 md:h-1/2 drop-shadow-2xl",
            },
            {
                "id": "16",
                "city": "zurich",
                "color": "zurich",
                "issue": "#16",
                "url": "src/assets/images/zurich.webp",
                "sectionCss": "snap-start w-full h-screen flex items-center justify-center bg-zurich",
                "imgCss": "w-auto h-1/3 md:h-1/2 drop-shadow-2xl",
            },
            {
                "id": "17",
                "city": "miami",
                "color": "miami",
                "issue": "#17",
                "url": "src/assets/images/miami.webp",
                "sectionCss": "snap-start w-full h-screen flex items-center justify-center bg-miami",
                "imgCss": "w-auto h-1/3 md:h-1/2 drop-shadow-2xl",
            },
            {
                "id": "18",
                "city": "tokyo",
                "color": "tokyo",
                "issue": "#18",
                "url": "src/assets/images/tokyo.webp",
                "sectionCss": "snap-start w-full h-screen flex items-center justify-center bg-tokyo",
                "imgCss": "w-auto h-1/3 md:h-1/2 drop-shadow-2xl",
            },
            {
                "id": "19",
                "city": "buenos-aires",
                "color": "buenos-aires",
                "issue": "#19",
                "url": "src/assets/images/buenos-aires.webp",
                "sectionCss": "snap-start w-full h-screen flex items-center justify-center bg-buenos-aires",
                "imgCss": "w-auto h-1/3 md:h-1/2 drop-shadow-2xl",
            },
            {
                "id": "20",
                "city": "istanbul",
                "color": "istanbul",
                "issue": "#20",
                "url": "src/assets/images/istanbul.webp",
                "sectionCss": "snap-start w-full h-screen flex items-center justify-center bg-istanbul",
                "imgCss": "w-auto h-1/3 md:h-1/2 drop-shadow-2xl",
            },
            {
                "id": "21",
                "city": "seoul",
                "color": "seoul",
                "issue": "#21",
                "url": "src/assets/images/seoul.webp",
                "sectionCss": "snap-start w-full h-screen flex items-center justify-center bg-seoul",
                "imgCss": "w-auto h-1/3 md:h-1/2 drop-shadow-2xl",
            },
            {
                "id": "22",
                "city": "detroit",
                "color": "detroit",
                "issue": "#22",
                "url": "src/assets/images/detroit.webp",
                "sectionCss": "snap-start w-full h-screen flex items-center justify-center bg-detroit",
                "imgCss": "w-auto h-1/3 md:h-1/2 drop-shadow-2xl",
            },
        ]

    }
}